name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
      
    - name: Restore dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build
      
    - name: Install Playwright Browser Emulators
      run: pwsh GoogleMapsTests/bin/Debug/net7.0/playwright.ps1 install  
      
    - name: Run tests
      run: dotnet test
