name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Run tests
      run: dotnet test ./GoogleMapsTests/src/Tests
